### ISSUE TITLE
3D simplex noise exhibiting spacial artifacts not found in 2D simplex noise

### ISSUE THREAD

**Issue by timscaffidi** [ashima/webgl-noise#10]
Hi,I've notice that the 3D snoise function produces very noticeable diagonal streaking that doesn't seem to appear (or not as noticeably) in the 2D snoise.

Compare the following revisions of this sandbox sketch:
[2D Simplex](http://glsl.heroku.com/e#18112.1)
[3D Simplex](http://glsl.heroku.com/e#18112.2)

The streaks exist in the 3D version even without an animation (just setting the z component to a constant).

Why does this happen and is there a way to minimize the effect?

**Comment by stegu** [comment]
Note my upload of "psrdnoise2D.glsl" yesterday. Analytical derivatives are reasonably straightforward to compute for simplex noise in all dimensions. There's also another open issue in this tracker about gradients for 3D noise. That thread contains a solution to computing the gradient of 3D noise.

**Comment by jjxtra** [comment]
What are the odds of a psrdnoise3D.glsl being created?

**Comment by stegu** [comment]
I made a C version of 3D flow noise back in 2005 or thereabouts, but it's
kind of ugly, in the sense that the gradients are not strictly uncorrelated
through the rotations, making it at least potentially unsuitable for
particle flow animations. I never had anyone express any interest in it, so
I dropped it. It did look OK when used for 3D texturing, though. If you
think a GLSL version would be useful, I would say the odds of it being
created are at least fair.

I have some time on my hands over the next few weeks. I will use some of it
to take a good look at my old C code and try to port it to GLSL.

**Comment by jjxtra** [comment]
@stegu If you do get it, let me know I will tip you a LARGE beer

**Comment by stegu** [comment]
I'm still trying to find time (and, more importantly, focus) to actually sit down and code this. I have an algorithm for "psrdnoise3D.glsl" worked out since months back, and it's not much more computationally intensive than plain 3D simplex noise with gradients. The conundrum of finding a simplex grid that still tiles over rectangular periods is solved, with some slight restrictions on the choice of period. So, you could say I'm currently at the point of having a solution for "psdnoise3D.glsl", without the "r" part, although not yet coded in GLSL. However, I still need to find a permutation function to create a good distribution of gradient rotation axes for the 3D "swirling" motion. My first naive attempt did not turn out well, but that can be fixed. Probably even "brute force and ignorance" will do the trick, just testing a lot of variations to see what works.

**Comment by unicomp21** [comment]
@stegu I am so sorry to hear this, hope you get to feeling better soon.

My father also got hit w/ covid, his health wasn't that great to begin with, so he was at a disadvantage.
http://c100k.blogspot.com/2020/12/covid-happens.html

Does adding an offset, and keeping all coordinates positive fix the issue?  I seem to remember this helping.

For anyone interested, there are some nice periodic implementations, but not as fast, over in https://github.com/aqsis/aqsis/blob/883cc9e027108d596437e231f6d05ef01d0cdda8/libs/math/noise.cpp

**Comment by unicomp21** [comment]
The point I'm trying to make above, is much can be done w/ tiled, in memory, noise textures.

**Comment by stegu** [comment]
Textures are certainly good for many applications, even as part of the
toolbox to create better permutations with a more "controlled" randomness,
so to speak. Designers of high-end GPU architectures spend a lot of effort
on making the texture subsystem fast and efficient, and in many cases it's
detrimental to performance if you don't make good use of that resource.
However, the point of this repository is to provide purely computational
noise, for the applications where that is to be preferred, so I won't dive
too deeply into the use of textures here.

**Comment by stegu** [comment]
A functioning "psrdnoise3D.glsl" now exists, but I will submit a journal article about it before I publish it here. Pardon the hassle, but this was non-trivial enough to at least try getting it published in a peer reviewed journal. The article is being written, and I will not dally, but if you want a preview of the function, let me know and I can send it to you in "private confidential communication". For legal purposes, that would require you to give me a "real" e-mail contact address. Sending it through the GitHub messaging system would make it untraceable. Please send your contact information to "stefan.gustavson@gmail.com".

**Comment by unicomp21** [comment]
@stegu will it be open source?  Can I use it for this task I have open in babylon.js?

https://github.com/BabylonJS/Babylon.js/issues/10446

**Comment by unicomp21** [comment]
@stegu So I can buy a copy, which journal?

**Comment by stegu** [comment]
In the middle of that wall of text, I wrote: "It will be an MIT license
like the rest of my GLSL noise functions." So, yes. Just keeping it a
little under cover for now.

I'm aiming for JCGT (http://jcgt.org/), because they are quick, well
respected and widely read, but I don't know if it will be accepted. They
are an open access online journal, no need to buy anything if they decide
to accept. But they are pretty picky with their content, so I might be
aiming too high. We'll see.

**Comment by stegu** [comment]
While waiting for the article review, I have retrofitted one important change to the permutations that should reduce the problems with diagonal streaks quite considerably. I am not sure they are eliminated, but they are definitely a lot less common. All functions in the repo have been updated.

**Comment by unicomp21** [comment]
Thanks!  Currently I’m away from keyboard, in Alaska.  Does this apply to
4d noise too?

**Comment by unicomp21** [comment]
With respect to calculating gradients, has anything changed?

**Comment by stegu** [comment]
Basically everything has changed in the new and improved version, but the
repo doesn't have it yet, as the article about it is still under review and
I need to keep the code reasonably under wraps a little while longer. I
just changed the permutation, which was a very small but important change
that should get rid of the most prominent flaw of the old version. All
version of all kinds of noise are affected by this change, and hopefully
improved as well. I have not tested 4-D noise properly in all planes all
across its huge domain, but please tell me if there are problems with it
still.

What will arrive once the article is accepted for publication somewhere is
2-D and 3-D versions of periodic (tiling) simplex noise with a very
flexible choice of tile size, an option to rotate the gradients in place à
la "flow noise", extended to 3-D, with analytic gradients and (optionally)
analytic second order derivatives. An updated version of 4-D noise is not
planned for the short term, but some of the changes, like the periodicity
and the analytic gradient, can most likely be retrofitted with a reasonable
effort. The 3-D tiling grid and the "flow noise" option can each solve some
of the problems that previously required 4-D noise, so you might want to
have a look at that.

  /Stefan

**Comment by stegu** [comment]
JCGT article to appear soon. These things take time, unfortunately, but now the article is accepted, only awaiting final approval after some wisely suggested revisions, and then it's time for a final touch-up session with the language editor. Yes, JCGT has a language editor, even though they are an open access journal run on a very low budget on a volunteer basis. Their peer reviewers were awesome as well. It really is a great journal.

**Comment by unicomp21** [comment]
@stegu is it ok to start using it publicly?  (the email version) Or better to wait?  I'm starting to play around w/ webgpu.

**Comment by stegu** [comment]
Still awaiting a formal final approval. Once it's formally cleared, I'm
fine with having the code appear in public with a note "to appear" rather
than "as seen in".
It should only be a matter of days now. The editor-in-chief is making his
final read-through. I'll let you know, and then I will hopefully have an
expected publication date as well.

Thanks for your patience. I have a bunch of fun demos I am itching to put
online as well. If you feel like sending me some links to interesting
experiments, we can list them in the repository. I will most likely be
updating that Github repo (TBA) regularly with my own demos and tutorials
over the next few months.

Den sön 14 nov. 2021 13:21John Davis ***@***.***> skrev:

**Comment by unicomp21** [comment]
@stegu no worries.  Thanks for this incredible gift to the planet.  If I'm lucky enough to create a noteworthy demo, I'll be sure and share it.  Thanks!

**Comment by stegu** [comment]
Entering final editing phase for that article. Publishing is a slow grind, but I want peer review publications to maintain a high standard, and being unhurried is a good and proven way. The repo is going to be github.com/stegu/psrdnoise/, but the 3-D code isn't there yet. Real soon now...
