### ISSUE TITLE
Mention the range somewhere

### ISSUE THREAD

**Issue by mruegenberg** [ashima/webgl-noise#16]
Some people implement noises to be between 0 and 1, other implementations (liket the Simplex noise here?) are between -1 and 1.

It would be helpful to just mention the range somewhere, so no one is left guessing.

**Comment by stegu** [comment]
Yes, we should mention that. Thanks for the suggestion.

Having said that, noise with a range 0 to 1 is what interactive material
editors and some shading language wrappers have been providing for
convenience, but the underlying "raw" function as such has always been zero
mean.
​

**Comment by stegu** [comment]
Mentioned it prominently on the wiki page. I think that's enough, I won't touch the source files for now.
