### ISSUE TITLE
Period z is ignored for float pnoise(vec3 P, vec3 rep)

### ISSUE THREAD

**Issue by jjxtra** [ashima/webgl-noise#20]
Doesn't matter what rep.z is, it appears to be ignored. Is this a feature or a bug?

**Comment by stegu** [comment]
It's clearly a bug. I'll look into that. Thanks for catching it!

**Comment by stegu** [comment]
The repetition period must be an exact integer, yes. It's not terribly well
documented, but the function works exactly like the "pnoise" function in
Renderman SL. Making the pattern periodic without seams with a non-integer
repetition period would be, well, nontrivial, and it goes quite a bit
beyond what I was aiming for.
