### ISSUE TITLE
Making perturbed normal bumps

### ISSUE THREAD

**Issue by unicomp21** [ashima/webgl-noise#24]
Hi @stegu @ijm 

Any chance I could beg for your help on this one?  We're having trouble making bumps w/ perturbed normals in babylon.js, would be grateful for your expertise.  Here is the discussion link.  Trying to make a simple example where the perturbed normal bumps look good, like in Fig. 5-11.

https://forum.babylonjs.com/t/discontinuities-in-simplex-noise/20611/12

**Comment by unicomp21** [comment]
@snowymo @sebastianherscher any chance Dr. Perlin is available? ^^

**Comment by stegu** [comment]
Have you seen this short PDF of mine? With analytic gradients, normal
perturbation is really very simple. You just need to remember to scale the
gradient with the inner derivative of the 3D texture coordinates. I
reinvented this particular wheel before I found the reference, but first
publishing credit goes to Morten Mikkelsen (his PhD thesis from 2008).

https://weber.itn.liu.se/~stegu76/TNM084-2019/bumpmapping/bumpmapping.pdf

Some demo source code is in the link below. It's a file for Shadron, a very
convenient tool for shader programming experiments, but the ".shadron" file
is a plain text file with GLSL code included. It has code for recomputing
normals at the vertex level (displacement mapping) as well as at the
fragment level (bump mapping), using the same expressions for both. (Note
that the noise function is in its separate .glsl file, which may or may not
be identical to a file with the same name in the "webgl-noise" repo.)
https://weber.itn.liu.se/~stegu76/TNM084-2019/shadron

  /Stefan G

**Comment by unicomp21** [comment]
Thanks @stegu !

**Comment by unicomp21** [comment]
@stegu is that the same as 5.6?

https://developer.nvidia.com/gpugems/gpugems/part-i-natural-effects/chapter-5-implementing-improved-perlin-noise

**Comment by stegu** [comment]
That article uses the same bump computation, yes, although it doesn't
explain how it works.

**Comment by unicomp21** [comment]
Thanks.  Is there any way to get a 5th order interpolation between mesh.position's in the shader?  When using webgl?

**Comment by stegu** [comment]
I am sorry for my mushy brain: the perturbation cretated by subtracting the
gradient from the normal without first projecting it to the surface tangent
plane is wrong. Looks OK but does not correspond to any analytical surface
normal. The projection described in my PDF and in Mikkelsen is the correct
way to do it, and it is only a small amount of extra work.

I don't quite understand what you mean by a 5th order interpolation of mesh
positions. The 5th order polynomial requires an input of 0..1, and that can
of course be achieved by texture coordinates or the like. The interpolation
is created in code, and if I'm not misremembering things, that is what my
implementations of "classic noise" are doing in the webgl-noise repo.

Analytic gradients are a lot less work than finite difference
approximations for simplex noise, but for classic noise the expressions for
the derivative get quite nasty. I would not recommend that.

**Comment by unicomp21** [comment]
>and that can of course be achieved by texture coordinates or the like
I get the gist of what's being said, but not sure I could implement it.  Any links/recommendations for reading?

**Comment by unicomp21** [comment]
Exactly what I was looking for, thanks @stegu!

**Comment by unicomp21** [comment]
@stegu see the distortion at the poles, on the sphere?

https://nodematerial-editor.babylonjs.com/#ND6Z9D#6

Think I'm not transforming the gradient properly?  Any idea how I can fix it?  Not sure how to transform into tangent space.

**Comment by stegu** [comment]
I prefer not to transform to gradient space at all. World space 3D noise
makes that possible to avoid. See the PDF I linked to originally. It really
is a lot less cumbersome. Tangent space at the poles of a sphere with
lat-long mapping is not well defined -- a classic problem you just won't
have with 3D bump mapping.

**Comment by unicomp21** [comment]
@stegu I didn't realize that, thanks!

**Comment by stegu** [comment]
Sorry for the confusion. My PDF was written for my students, and it
includes a repetition of the tangent space method. I forgot to say "page 3
has the juicy bits".

  /Stefan G
