### ISSUE TITLE
demo fails to build on OS X

### ISSUE THREAD

**Issue by ghost** [ashima/webgl-noise#7]
I get the following failure when trying to run the makefile in the demos folder:

```
$ make MacOSX
cd common ; make
make[1]: Nothing to be done for `all'.
cd MacOSX ; make ; make run
cc -I. -I/usr/X11/include   -c -o noisedemo.o ../common/noisedemo.c
cc -framework Cocoa -framework OpenGL -lglfw  noisedemo.o   -o noisedemo
./bundle.sh noisedemo.app noisedemo ; chmod a-x noisedemo
/bin/sh: ./bundle.sh: Permission denied
ln -s ../common/noisedemo.vert ../common/noisedemo.frag . ; touch links_done
open -W ./noisedemo.app
The file /Volumes/ssd/code/graphics/webgl-noise/demo/MacOSX/noisedemo.app does not exist.
make[1]: *** [run] Error 1
make: *** [MacOSX] Error 2
```

doing:

```
$ chmod u+x demo/MacOSX/bundle.sh
```

fixes the 'Permission denied' error above and allows the Makefile to run flawlessly

**Comment by stegu** [comment]
By now, that demo is abandoned code. I have not touched it in years, and it probably won't compile on any platform any longer without tweaks. I am closing the issue, but it will remain unresolved unless someone commits a complete fix. I no longer have access to a MacOS system myself.
